AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'specifications/fixtures/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'specifications/**/*'

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
