#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) if Dir.exist?(lib_path)

require 'ruby_md_ssg'

RubyMdSsg::CLI.start(ARGV)
