#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup' if File.exist?(File.expand_path('../Gemfile', __dir__))

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) if Dir.exist?(lib_path)

require 'static_ruby'

StaticRuby::CLI.start(ARGV)
