name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to release (e.g., 0.2.0)'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Run test suite
        run: bundle exec ruby bin/test

      - name: Build gem
        run: |
          gem build ruby-md-ssg.gemspec

      - name: Publish to RubyGems
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem
          cat <<CREDENTIALS > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          CREDENTIALS
          chmod 0600 ~/.gem/credentials
          gem push ruby-md-ssg-*.gem
